### ISSUE TITLE
Is it possible to get Ratcliff-Obershelp similarity implemented?

### ISSUE THREAD

**Issue by luka-TU** [vanessaklee/akin#5]
Hi,

Is this project still active?

Best,
Luka

**Comment by vanessalee-papa** [comment]
I am happy to accept PRs! I'll also add it to my list if you aren't able to implement it before me.

**Comment by luka-TU** [comment]
@vanessalee-papa thank you for the response! got it. Hopefully I will be able to carve out some time to add it.

Also, could you take a look at this small PR, please? 🙇

**Comment by vanessaklee** [comment]
Hi, I'll take a look this week. Thank you!

**Comment by luka-TU** [comment]
@vanessaklee sorry, totally forgot to post the link to the PR: https://github.com/vanessaklee/akin/pull/6.
